Repository Hitoru141/EsportsWebsite, pull requests merged in 2023-09, with the labels that each got.

#13 Changed Structure
  firebase.jsx
  src/Appdata/appdata.js
  src/Components/Carousel.jsx
  src/Views/Admin/AdCarousel.jsx
  src/Views/Admin/CarouselCards.jsx
  src/service/carouselHandler/deleteHandler.jsx
  src/service/carouselHandler/uploadHandler.jsx
Labels: enhancement

#20 Structure update
  src/Views/Admin/Admindash.jsx
  src/Views/Admin/Teams/Addteam/AdTeam.jsx
  src/Views/Admin/Teams/ViewTeams/ViewTeams.jsx
Labels: enhancement

#25 Delete teams#16
  package.json
  src/Views/Admin/Teams/Delete Team/DeleteTeam.jsx
  src/Views/Admin/Teams/ViewTeams/ViewTeams.jsx
  src/main.jsx
  src/service/deleteImageService.jsx
  src/service/teamsHandler/deleteTeamHandler.jsx
  yarn.lock
Labels: Feature

#24 Added TanstackQuery for easy access of data
  package.json
  src/Views/Admin/Teams/ViewTeams/ViewTeams.jsx
  src/main.jsx
  yarn.lock
Labels: enhancement

#23 Feature: Upload Banner/Logo + POST Team
  src/Styles/admin.css
  src/Views/Admin/Teams/Addteam/AdTeam.jsx
  src/Views/Admin/Teams/Addteam/postTeam.jsx
  src/service/bannerHandler/bannerUploadHandler.jsx
  src/service/carouselHandler/uploadHandler.jsx
  src/service/logoHandler/logoUploadHandler.jsx
Labels: Feature

#36 Add toastifier
  package.json
  src/Views/Admin/AdCarousel.jsx
  src/Views/Admin/CarouselCards.jsx
  src/Views/Admin/Teams/Addteam/AdTeam.jsx
  src/Views/Admin/Teams/Addteam/postTeam.jsx
  src/service/carouselHandler/deleteHandler.jsx
  src/service/carouselHandler/uploadHandler.jsx
  yarn.lock
Labels: enhancement

#37 added member cards components with props
  src/App.jsx
  src/Styles/admin.css
  src/Styles/cards.css
  src/Views/Admin/AddTeamComponents/ManageMembers.jsx
  src/Views/Admin/AddTeamComponents/MembersCard.jsx
  src/assets/MemProf.png
Labels: enhancement

#41 Added dynamic routing for manage members per team
  src/App.jsx
  src/Views/Admin/Teams/ViewTeams/ViewTeams.jsx
Labels: bug

#45 About page
  src/Components/ContCreatorsCard.jsx
  src/Components/ManagementCards.jsx
  src/Components/Navbar.jsx
  src/Components/TeamCard.jsx
  src/Styles/hero.css
  src/Styles/main.css
  src/Views/About.jsx
  src/Views/Home.jsx
  src/assets/ASTBanner.jpg
  src/assets/ASTLanpic.jpg
  src/assets/PresidentTestPic.jpg
  src/assets/cosmos.gif
Labels: Feature

#44 Feature login #42
  firebase.jsx
  package.json
  src/App.jsx
  src/Recoil/token.js
  src/Views/Admin/AdCarousel.jsx
  src/Views/Admin/Admindash.jsx
  src/Views/Admin/Auth/AdminSignIn.jsx
  src/main.jsx
  yarn.lock
Labels: Feature

#50 Add member form component
  src/Styles/admin.css
  src/Styles/cards.css
  src/Views/Admin/AddTeamComponents/AddMemberForm.jsx
  src/Views/Admin/AddTeamComponents/ManageMembers.jsx
  src/Views/Admin/AddTeamComponents/MembersCard.jsx
  src/Views/Admin/Teams/Addteam/AdTeam.jsx
  src/Views/ValorantTeam.jsx
  src/service/imageUploadService.jsx
  src/service/memberHandler/postMember.jsx
Labels: enhancement
